-- Table: public.uploads

CREATE TABLE IF NOT EXISTS public.uploads
(
    uid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_cid character(46),
    metadata_cid character(46),
    extra_cids jsonb,
    status text NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'CONFIRMED', 'DISMISSED')),
    uploaded_at timestamptz NOT NULL DEFAULT now(),
    purged boolean DEFAULT false
);