CREATE TABLE IF NOT EXISTS public.uploads
(
    uid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_cid character(46),
    metadata_cid character(46),
    extra_cids jsonb,
    status text NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'CONFIRMED', 'DISMISSED')),
    uploaded_at timestamptz NOT NULL DEFAULT now(),
    purged boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.upload_sessions 
(
    uid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    creator_address character(42) NOT NULL
    CHECK (
        creator_address ~ '^0x[a-fA-F0-9]{40}$'
    ),
    started_at timestamptz NOT NULL DEFAULT now(),
    short_video_completed boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'COMPLETED', 'EXPIRED'))
);

CREATE TABLE IF NOT EXISTS public.short_videos
(
    upload_session_id UUID PRIMARY KEY,
    original text NOT NULL,
    standardized text,
    standardized_cid varchar(66),
    mid_res text,
    mid_res_cid varchar(66),
    low_res text,
    low_res_cid varchar(66),
    is_copyright_free boolean,
    is_explicit_free boolean
);

CREATE OR REPLACE FUNCTION update_short_video_status()
RETURNS trigger AS $$
BEGIN
    IF NEW.standardized IS NOT NULL
        AND NEW.standardized_cid IS NOT NULL
        AND OLD.status = 'PENDING'
    THEN
        NEW.status := 'COMPLETED';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_short_video_status
BEFORE UPDATE ON public.short_videos
FOR EACH ROW
EXECUTE FUNCTION update_short_video_status();