CREATE TABLE IF NOT EXISTS public.uploads
(
    uid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_cid character(46),
    metadata_cid character(46),
    extra_cids jsonb,
    status text NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'CONFIRMED', 'DISMISSED')),
    uploaded_at timestamptz NOT NULL DEFAULT now(),
    purged boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.upload_sessions 
(
    uid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_address character(42) NOT NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    content_uris jsonb
    CHECK (
        creator_address ~ '^0x[a-fA-F0-9]{40}$'
    ),
    status text NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'EXPIRED'))
);